fl_dashboard/urls.py
from django.urls import path
from django.views.generic import TemplateView

from . import views

app_name = "dashboard"
urlpatterns = [
    path('', views.home, name="home"),
    path('alerts/', views.alerts, name="alerts"),
    path('reports/daily', views.daily_reports, name="daily_reports"),
    path('reports/monthly', views.monthly_reports, name="monthly_reports"),
    path('reports/overview', views.overview_reports, name='reports_overview'),

    path('viewmodel', views.DashboardJson.as_view(), name="viewmodel"),

    path('chlorine-level', TemplateView.as_view(template_name='fl_dashboard/dashboard/reports/chlorine-level.html')),

    path('pulses/flow', views.FlowPulsesHistory.as_view(), name="flow_pulses_history"),

    path('detected-anomalies', views.detected_anomalies, name="detected-anomalies-report"),

    path('pulses/pressure', TemplateView.as_view(template_name='fl_dashboard/dashboard/pressure_pulses_history.html'),
         name="pressure_pulses_history"),

    path('meters', TemplateView.as_view(template_name='fl_dashboard/dashboard/meters_list.html'),
         name="meters_list"),
    path('pressure-transmitters', TemplateView.as_view(template_name='fl_dashboard/dashboard/pressure_transmitters.html'),
         name="pressure_transmitters_list"),
    path('pressure-readings', TemplateView.as_view(template_name='fl_dashboard/dashboard/pressure_readings.html'),
         name="pressure_readings"),
    path('consumption/bulk', TemplateView.as_view(template_name='fl_dashboard/dashboard/bulk_consumption.html'),
         name="bulk_consumption"),
    path('consumption/detailed', TemplateView.as_view(template_name='fl_dashboard/dashboard/detailed_consumption.html'),
         name="detailed_consumption"),
]

fl_meters/urls.py
from django.urls import include, path
from django.views.generic import TemplateView
from rest_framework.routers import SimpleRouter

from . import views

router = SimpleRouter()
router.register(r'pulse', views.PulseViewSet)
router.register(r'pressure', views.PressurePulseViewSet)
router.register(r'chlorine', views.ChlorinePulseViewSet)

app_name = "api"
urlpatterns = [
    path('new-meter/', views.ConfigView.as_view()),
    path('meters-summary/', views.MetersSummary.as_view()),
    path('meters-list/', views.MetersList.as_view()),
    path('transmitters-list/', views.PressureTransmittersList.as_view()),
    path('alerts-summary/', views.AlertsSummary.as_view()),
    path('bulk-meters-consumption/', views.BulkMetersConsumption.as_view(), name='bulk-meters-consumption'),
    path('detailed-meters-consumption/', views.DetailedMetersConsumption.as_view(), name='detailed-meters-consumption'),
    path('pressure-readings/', views.PressureReadings.as_view()),
    path('zones/', views.ZonesList.as_view()),
    path('transmission-lines/', views.TransmissionLinesList.as_view()),

    path('daily-reports-data/', views.daily_reports_data),
    path('monthly-reports-data/', views.monthly_reports_data),
    path('consumption-hours-ago/', views.consumption_of_hours_ago, name='consumption-hours-ago'),
    path('recent_qh/', views.recent_qh),

    path('analytics/flow-consumption/', views.flow_consumption_history),
    path('analytics/azp/', views.azp_history),
    path('pulses-history/flow/', views.flow_pulses_history),
    path('pulses-history/pressure/', views.pressure_pulses_history),

    path('unix-time/', views.unix_time),
    path('unix-pulse/', views.UnixStampedPulse.as_view()),
    path('unix-pressure-pulse/', views.UnixStampedPressurePulse.as_view()),

    path('stats/overview', views.overview_report_data),
    path('stats/narrated-pressure-levels-overview-data/', views.narrated_pressure_levels_overview_data),
    path('stats/narrated-chlorine-levels', views.narrated_chlorine_level, name="narrated-chlorine-levels"),

    path('detected-anomalies/', views.detected_anomalies, name="detected-anomalies"),

    path('flow-meter/narrate', views.flow_meter_narrate, name="flow-meter-narrate"),
]

flowless_dashboard/urls.py
from django.contrib import admin
from django.urls import include, path, reverse_lazy
from rest_framework import routers
from django.views.generic.base import RedirectView

import fl_meters.urls as fl_meters_urls

router = routers.DefaultRouter()
router.registry.extend(fl_meters_urls.router.registry)

# Customize Admin panel titles
admin.site.site_header = "Flowless Administration"
admin.site.site_title = "Flowless Admin"
admin.site.index_title = "Admin Panel"
admin.site.site_url = reverse_lazy('dashboard:home')

urlpatterns = [
    path('admin/', admin.site.urls, name='admin'),
    path('api/', include(router.urls)),       # DRF API endpoints
    path('api/', include('fl_meters.urls')),  # Custom API endpoints
    path('dashboard/', include('fl_dashboard.urls'), name='index'),
    path('', include('fl_dashboard.auth_urls'), name='auth'),
    path('', RedirectView.as_view(url='/dashboard/', permanent=True))
]

fl_dashboard/models.py
from django.db import models
from django_google_maps import fields as map_fields


class Preferences(models.Model):
    clientScreenName = models.CharField(max_length=80, default='')
    address = map_fields.AddressField(max_length=200, null=True, verbose_name='Map Center Address')
    geolocation = map_fields.GeoLocationField(max_length=100, null=True, verbose_name='Map Center Coords')
    mapZoom = models.IntegerField(default=15, verbose_name='Map Zoom Level')

fl_dashboard/views.py
from functools import reduce

from django.contrib.auth.decorators import login_required
from django.db.models import Value as V, Sum
from django.db.models.functions import Coalesce
from django.utils.timezone import utc
from django.views.generic import TemplateView
from rest_framework.response import Response
from django.shortcuts import render
from rest_framework.views import APIView

from fl_meters.models import Zone, LossRecord, Notification
from fl_meters.tools import get_day_opening, get_day_start
from . import models
from .tools import *


@login_required
def home(request):
    context = homepage_stats()
    context.update({
        'alert_notifications': Notification.objects.filter(user=request.user, alert__isnull=False).count()
    })
    return render(request, template_name='fl_dashboard/dashboard/home.html', context=context)

@login_required
def overview_reports(request):
    from .customization import overview_report
    context = {
        'narration_charts': overview_report['narration_charts'],
        'pies': overview_report['pies']
    }
    return render(request, template_name='fl_dashboard/dashboard/reports/overview.html', context=context)

@login_required
def daily_reports(request):
    today = get_day_start(get_now())
    today_consumption = DailyZoneConsumption.objects.filter(date=today).aggregate(Sum('consumption'))['consumption__sum']
    today_consumption = round(today_consumption, 2) if today_consumption is not None else '---'
    today_avg = DailyAvgConsumption.objects.filter(day_of_week=today.weekday()).aggregate(Avg('amount'))['amount__avg']
    today_avg = round(today_avg, 2) if today_avg is not None else '---'

    yesterday = today - dt.timedelta(days=1)
    yesterday_loss = LossRecord.objects.filter(date=yesterday).aggregate(Sum('amount'))['amount__sum']
    if yesterday_loss is None:
        yesterday_loss = '---'
        yesterday_loss_percentage = None
    else:
        yesterday_consumption = DailyZoneConsumption.objects.filter(date=yesterday).aggregate(Sum('consumption'))['consumption__sum']
        try:
            yesterday_loss_percentage = str(round(yesterday_loss / yesterday_consumption, 2) * 100) + "%"
        except:  # catches: yesterday_consumption == 0, or yesterday_consumption == None
            yesterday_loss_percentage = None

    context = {
        'list_of_months': list(range(1, 13)),
        'list_of_days': list(range(32)),
        'this_year': today.year,
        'this_month': today.month,
        'this_day': today.day,
        'today_consumption': today_consumption,
        'today_avg': today_avg,
        'yesterday_loss': yesterday_loss,
        'yesterday_loss_percentage': yesterday_loss_percentage
    }
    return render(request, template_name='fl_dashboard/dashboard/daily_reports.html', context=context)


@login_required
def monthly_reports(request):
    today = get_now()
    from datetime import datetime
    beginning_of_month = datetime(today.year, today.month, 1).replace(tzinfo=utc)

    month_consumption = 1  # prevents division by zero exception in new systems
    month_nrw = 0
    all_zones = Zone.objects.all()
    for zone in all_zones:
        month_record = MonthlyZoneConsumption.objects.filter(zone_id=zone, date=beginning_of_month).first()
        month_consumption += month_record.consumption if month_record is not None else 0
        month_nrw += reduce(
            lambda acc, record: record.amount + acc,
            LossRecord.objects.filter(zone=zone, date__gte=beginning_of_month),
            0)

    context = {
        'month_consumption': round(month_consumption, 2),
        'month_nrw_percentage': round(month_nrw / month_consumption * 100, 2),
        'burst_alerts': "---",
        'year': today.year,
        'month': today.month,
        'list_of_months': list(range(1, 13))
    }
    return render(request, template_name='fl_dashboard/dashboard/monthly_reports.html', context=context)

@login_required
def alerts(request):
    Notification.objects.filter(user=request.user).delete()
    return render(request, template_name='fl_dashboard/dashboard/alerts.html')

def detected_anomalies(request):
    ctx = {
        'meters': Meter.objects.all()
    }
    return render(request, template_name='fl_dashboard/dashboard/detected_anomalies.html', context=ctx)

class FlowPulsesHistory(TemplateView):
    template_name = 'fl_dashboard/dashboard/flow_pulses_history.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data()
        context.update({
            'meters': Meter.objects.all()
        })
        return context


class DashboardJson(APIView):
    authentication_classes = ()
    permission_classes = ()

    def get(self, request, format=None):
        prefs, created = models.Preferences.objects.get_or_create(id=1, defaults={'geolocation': '0,0'})

        return Response({
            'mapCenterLat': prefs.geolocation.lat,
            'mapCenterLng': prefs.geolocation.lon,
            'mapZoomLevel': prefs.mapZoom,
            'mapTypeId': 'hybrid',
        })

fl_dashboard/templates/fl_dashboard/dashboard/bulk_consumption.html
{% extends 'fl_dashboard/dashboard/base.html' %}
{% load staticfiles %}

{% block title %}Latest Bulk Consumption{% endblock title %}

{% block content-title %}Latest Bulk Consumption{% endblock %}

{% block content %}
<!-- Datatable -->
<div class="card shadow mb-4">
  <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
    <h6 class="m-0 font-weight-bold text-primary">Overview</h6>
  </div>
  <div class="card-body">
    <div class="table-responsive">
      <table class="table table-bordered dataTable" id="dataTable" width="100%" cellspacing="0" role="grid" style="width: 100%;">

        <thead>
          <tr role="row">
            <th class="sorting_asc">Meter Key</th>
            <th class="">Latest Reading <small>m<sup>3</sup></small></th>
            <th class="">Latest Reading Time</th>
            <th class="">Previous Reading <small>m<sup>3</sup></small></th>
            <th class="">Previous Reading Time</th>
            <th class="">Consumption <small>m<sup>3</sup></small></th>
          </tr>
        </thead>

        <tbody></tbody>

      </table>
    </div>
  </div>
</div>
{% endblock %}

{% block scripts %}
    {{ block.super }}
    <script src="{% static 'fl_dashboard/vendor/datatables/jquery.dataTables.min.js' %}"></script>
    <script src="{% static 'fl_dashboard/vendor/datatables/dataTables.bootstrap4.min.js' %}"></script>
    <script>
        $('#dataTable').DataTable({
            'ajax': {
                url: '{% url 'api:bulk-meters-consumption' %}?format=json',
                method: "GET",
            },
            columns: [
                    { data: "meter_key" },
                    { data: "last_reading" },
                    { data: "last_time" },
                    { data: "previous_reading" },
                    { data: "previous_time" },
                    { data: "consumption" },
            ],
            rowCallback: function( row, data, index ) {
                if (data.status == "Not Handled") {
                    $('td', row).addClass('row-danger');
                }{% comment %}else{
                    $('td', row).addClass('row-success');
                }{% endcomment %}
            },
        })
    </script>
{% endblock %}

fl_dashboard/templates/fl_dashboard/dashboard/detailed_consumption.html
{% extends 'fl_dashboard/dashboard/base.html' %}
{% load staticfiles %}

{% block title %}Latest Customer Consumption{% endblock title %}

{% block content-title %}Latest Customer Consumption{% endblock %}

{% block content %}
<!-- Datatable -->
<div class="card shadow mb-4">
  <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
    <h6 class="m-0 font-weight-bold text-primary">Overview</h6>
  </div>
  <div class="card-body">
    <div class="table-responsive">
      <table class="table table-bordered dataTable" id="dataTable" width="100%" cellspacing="0" role="grid" style="width: 100%;">

        <thead>
          <tr role="row">
            <th class="sorting_asc">Meter Key</th>
            <th class="sorting_asc">Customer Name</th>
            <th class="sorting_asc">Last Reading</th>
            <th class="sorting_asc">Last Reading Time</th>
            <th class="sorting_asc">Previous Reading</th>
            <th class="sorting_asc">Previous Reading Time</th>
{% comment %}
            <th class="sorting_asc">Consumption</th>
            <th class="sorting_asc">Avg. Consumption</th>
            <th class="sorting_asc">Alerts No.</th>
{% endcomment %}
          </tr>
        </thead>

        <tbody></tbody>

      </table>
    </div>
  </div>
</div>
{% endblock %}

{% block scripts %}
    {{ block.super }}
    <script src="{% static 'fl_dashboard/vendor/datatables/jquery.dataTables.min.js' %}"></script>
    <script src="{% static 'fl_dashboard/vendor/datatables/dataTables.bootstrap4.min.js' %}"></script>
    <script>
        $('#dataTable').DataTable({
            'ajax': {
                url: '{% url 'api:detailed-meters-consumption' %}?format=json',
                method: "GET",
            },
            columns: [
                    { data: "meter_key" },
                    { data: "customer_name" },
                    { data: "last_reading" },
                    { data: "last_time" },
                    { data: "previous_reading" },
                    { data: "previous_time" },
{% comment %}
                    { data: "consumption" },
                    { data: "average_consumption" },
                    { data: "alerts_no" },
{% endcomment %}
            ],
            rowCallback: function( row, data, index ) {
                if (data.status == "Not Handled") {
                    $('td', row).addClass('row-danger');
                }{% comment %}else{
                    $('td', row).addClass('row-success');
                }{% endcomment %}
            },
        })
    </script>
{% endblock %}

fl_dashboard/templates/fl_dashboard/dashboard/home.html
{% extends 'fl_dashboard/dashboard/base.html' %}
{% load staticfiles %}

{% block title %}Home{% endblock title %}

{% block content-title %}Dashboard{% endblock %}

{% block styles %}
<style>
    #map {
        width: 100%;
        min-height: 500px;
    }
</style>
{% endblock %}

{% block content %}

    <!-- At A Glace Row -->
    <div class="row">

      <!-- PERCENTAGE OF RECEIVED SIGNALS -->
      <div class="col-lg-4 mb-4">
        <div class="card border-left-success shadow h-100 py-2">
          <div class="card-body">
            <div class="row no-gutters align-items-center">
              <div class="col mr-2">
                <div class="text-xs font-weight-bold text-success text-uppercase mb-1">
                  Percentage of Received Pulses<br>(Last Hour)
                </div>
                <div class="row no-gutters align-items-center">
                  <div class="col-auto">
                    <div class="h5 mb-0 mr-3 font-weight-bold text-gray-800">{{ received_signals_percentage }}</div>
                  </div>
                  <div class="col">
                    <div class="progress progress-sm mr-2">
                      <div class="progress-bar bg-success" role="progressbar"
                           style="width: {{ received_signals_percentage }}"
                           aria-valuenow="78.6" aria-valuemin="0" aria-valuemax="100">
                      </div>
                    </div>
                  </div>
                </div>
              </div>
              <div class="col-auto">
                <i class="fas fa-satellite-dish fa-2x text-gray-300"></i>
              </div>
            </div>
          </div>
        </div>
      </div>

      <!-- LAST DAY LEAKAGE -->
      <div class="col-lg-4 mb-4">
        <a class="card border-left-primary shadow h-100 py-2" href="{% url 'dashboard:bulk_consumption' %}">
          <div class="card-body">
            <div class="row no-gutters align-items-center">
              <div class="col mr-2">
                <div class="text-xs font-weight-bold text-primary text-uppercase mb-1">
                  Today's Consumption<br>({{ n_zones }} Zone{% if n_zones != 1 %}s{% endif %})
                </div>
                <div class="h5 mb-0 font-weight-bold text-gray-800">{{ today_consumption }} m<sup>3</sup></div>
              </div>
              <div class="col-auto">
                <i class="fas fa-chart-area fa-2x text-gray-300"></i>
              </div>
            </div>
          </div>
        </a>
      </div>

      <!-- ALERTS -->
      <div class="col-lg-4 mb-4">
        <a class="card border-left-danger shadow h-100 py-2" href="{% url 'dashboard:alerts' %}">
          <div class="card-body">
            <div class="row no-gutters align-items-center">
              <div class="col mr-2">
                <div class="text-xs font-weight-bold text-danger text-uppercase mb-1">
                  <span>Alerts</span>
                </div>
                <div class="h5 mb-0 font-weight-bold text-gray-800">
                    {% if alert_notifications == 0 %}
                        No New Alerts
                    {% elif alert_notifications == 1 %}
                        1 New Alert
                    {% else %}
                        {{ alert_notifications }} New Alerts
                    {% endif %}
                </div>
              </div>
              <div class="col-auto">
                <i class="fas fa-exclamation-circle fa-2x text-gray-300"></i>
              </div>
            </div>
          </div>
        </a>
      </div>
    </div>

    <!-- Consumption Row -->
    <div class="row">

        <!-- Consumption Chart -->
        <div class="col-xl-8 col-lg-7">
            <div class="card shadow mb-4">
                <!-- Card Header - Dropdown -->
                <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
                    <h6 class="m-0 font-weight-bold text-primary">Hourly Flow Overview</h6>
                    {% comment %}
                    <div class="dropdown no-arrow">
                        <a class="dropdown-toggle" href="#" role="button" id="dropdownMenuLink"
                           data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            <i class="fas fa-ellipsis-v fa-sm fa-fw text-gray-400"></i>
                        </a>
                        <div class="dropdown-menu dropdown-menu-right shadow animated--fade-in"
                             aria-labelledby="dropdownMenuLink">
                            <div class="dropdown-header">Dropdown Header:</div>
                            <a class="dropdown-item" href="#">Action</a>
                            <a class="dropdown-item" href="#">Another action</a>
                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item" href="#">Something else here</a>
                        </div>
                    </div>
                    {% endcomment %}
                </div>
                <!-- Card Body -->
                <div class="card-body">
                    <div class="chart-area">
                        <canvas id="myAreaChart"></canvas>
                    </div>
                </div>
            </div>
        </div>

        <!-- Consumption Statistics -->
        <div class="col-xl-4 col-lg-5 d-flex">
            <div class="card shadow mb-4 flex-fill">
                <!-- Card Header - Dropdown -->
                <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
                    <h6 class="m-0 font-weight-bold text-primary">Consumption Statistics</h6>
                    <div class="dropdown no-arrow">
                        <a class="dropdown-toggle" href="#" role="button" id="dropdownMenuLink"
                           data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            <i class="fas fa-ellipsis-v fa-sm fa-fw text-gray-400"></i>
                        </a>
                        <div class="dropdown-menu dropdown-menu-right shadow animated--fade-in"
                             aria-labelledby="dropdownMenuLink">
                            <div class="dropdown-header">Dropdown Header:</div>
                            <a class="dropdown-item" href="#">Action</a>
                            <a class="dropdown-item" href="#">Another action</a>
                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item" href="#">Something else here</a>
                        </div>
                    </div>
                </div>
                <!-- Card Body -->
                <div class="card-body mx-3 my-2 d-flex flex-column justify-content-between">
                    <div>
                        <span class="pull-right">
                            <i class="fas fa-tachometer-alt fa-2x text-gray-300"></i>
                        </span>
                        <dl>
                            <dt class="h5 font-weight-bold">Accumulative Consumption</dt>
                            <dd class="mb-1 ml-1">Today's: {{ today_consumption }} m³</dd>
                            <dd class="mb-1 ml-1">Yesterday's: {{ yesterday_consumption }} m³</dd>
                            <dd class="mb-1 ml-1">This Month's: {{ month_consumption }} m³</dd>
                            <dt class="mt-3 h5 font-weight-bold">Average Consumption</dt>
                            <dd class="mb-1 ml-1">Average Daily: {{ daily_avg_consumption }} m³</dd>
                            <dd class="mb-1 ml-1">Average Monthly: {{ monthly_avg_consumption }} m³</dd>
                        </dl>
                    </div>
                    <span><a href="{% url 'dashboard:detailed_consumption' %}">Customers Consumption</a></span>
                </div>
            </div>
        </div>

        <!-- Overview Map -->
        <div class="col-sm-12 d-flex">
          <div class="card shadow mb-4 flex-fill">
            <div class="card-body mx-3 my-2 d-flex flex-column justify-content-between">
              <span class="h5 font-weight-bold text-center mb-4">Map Overview</span>
              <div id="map"></div>
            </div>
          </div>
        </div>
    </div>
{% endblock %}

{% block scripts %}
{{ block.super }} {# block.super renders all the necessary scripts from base.html #}
<script src="{% static 'fl_dashboard/vendor/chart.js/Chart.min.js' %}"></script>
<script src="{% static 'fl_dashboard/js/demo/dashboard-chart-bar.js' %}"></script>
<script src="{% static 'fl_dashboard/vendor/datatables/jquery.dataTables.min.js' %}"></script>
<script src="{% static 'fl_dashboard/vendor/datatables/dataTables.bootstrap4.min.js' %}"></script>

<script src="https://maps.googleapis.com/maps/api/js"></script>
<script>
  /** Google Map */
  let MAP;
  let positions = {
    qCenter: {lat: 32.0127145, lng: 35.1908548},
    salfit: {lat: 32.084924, lng: 35.180775},
    horseshoeTop: {lat: 32.012662, lng: 35.190096}
  };
  let zones_old = {
    horseshoe: [
      {lat: 32.010212, lng: 35.189781},
      {lat: 32.010309, lng: 35.190241},
      {lat: 32.010260, lng: 35.190688},
      {lat: 32.011212, lng: 35.190943},
      {lat: 32.011878, lng: 35.190973},
      {lat: 32.012340, lng: 35.190799},
      {lat: 32.012613, lng: 35.190179}, // horseshoeTop
      {lat: 32.012230, lng: 35.189478},
      {lat: 32.011973, lng: 35.189376},
      {lat: 32.011973, lng: 35.189376},
      {lat: 32.011973, lng: 35.189376},
      {lat: 32.011973, lng: 35.189376},
      {lat: 32.011150, lng: 35.189389},
    ],
    uptown: []
  };
  let zones = {};
  let metersData = [];
  let transmittersData = [];
  let markersObjects = []; // { marker, infoWindow }
  let viewModel = {
            'mapCenterLat': 0.0,
            'mapCenterLng': 0.0,
            'mapZoomLevel': 15,
            'mapTypeId': 'roadmap',
        };

  // fetch meters information
  $.ajax({
    url: "/api/meters-list/?format=json&onlyWithCoords=1",
    success: jsonData => {
      metersData = jsonData.data;
      console.log(metersData);
      setTimeout(() => createMarkersForMeters(), 500);
    }
  });
  // fetch transmitters information
  $.ajax({
    url: "/api/transmitters-list/?format=json&onlyWithCoords=1",
    success: jsonData => {
      transmittersData = jsonData.data;
      setTimeout(() => createMarkersForTransmitters(), 500);
    }
  });

  // fetch dashboard map settings
  $.ajax({
    url: "/dashboard/viewmodel",
    success: jsonData => {
      viewModel = jsonData;
      console.log('viewModel', viewModel);
      initMap();
    }
  });

  // fetch zones information
  $.ajax({
    url: "/api/zones/?format=json",
    success: jsonData => {
      zones = jsonData.data;
    }
  });

  function makeInfoWindow(device_type, key, link) {
    return new google.maps.InfoWindow({
      content:
        `<small>${device_type}</small> <br>` +
        `<b class="iw-title">${key}</b> <br><br>` +
        `<a style="text-decoration: underline; font-size:90%;" href="${link.url}">${link.text}</a>`
    });
  }

  function makeMarker(position, iconUrl = null) {
    let options = {
      position: position,
      map: MAP,

    };
    if(iconUrl){
      Object.assign(options, {
        icon: {
          url: iconUrl
        }
      })
    }

    return new google.maps.Marker(options);
  }

  function createMarkersForMeters() {
    for (let meter of metersData) {
      let marker = makeMarker({lat: parseFloat(meter.lat), lng: parseFloat(meter.lng)});
      let infoWindow = makeInfoWindow('Flow Meter', meter.meter_key, {text: "Latest Pulses", url:"{% url 'dashboard:bulk_consumption' %}"});

      marker.addListener('click', function (event) {
        console.log(event, this);
        infoWindow.open(MAP, marker);
      });

      markersObjects.push({marker: marker, infoWindow: infoWindow})
    }
  }

  function createMarkersForTransmitters() {
    for (let meter of transmittersData) {
      let marker = makeMarker(
          {lat: parseFloat(meter.lat), lng: parseFloat(meter.lng)},
          "http://maps.google.com/mapfiles/ms/icons/blue-dot.png"
      );
      let infoWindow = makeInfoWindow('Pressure Sensor', meter.meter_key, {text: "Latest Pulses", url: "{% url 'dashboard:pressure_readings' %}"});

      marker.addListener('click', function (event) {
        console.log(event, this);
        infoWindow.open(MAP, marker);
      });

      markersObjects.push({marker: marker, infoWindow: infoWindow})
    }
  }

  function initMap() {
    MAP = new google.maps.Map(document.getElementById('map'), {
      center: {lat: viewModel.mapCenterLat, lng: viewModel.mapCenterLng},
      zoom: viewModel.mapZoomLevel,
      mapTypeId: viewModel.mapTypeId,
      styles: [{
        featureType: "poi",
        stylers: [{visibility: "off"}]
      }]
    });

    MAP.addListener('click', function (e) {
      console.log(MAP, e);
    });

    // Construct the zones' polygons.
    setTimeout(() => {
      for (let zone_json of zones) {
        console.log(zone_json);
        let zone_obj = new google.maps.Polygon({
          paths: zone_json.coords,
          strokeColor: zone_json.hex_color,
          strokeOpacity: 0.8,
          strokeWeight: 2,
          fillColor: zone_json.hex_color,
          fillOpacity: 0.35,
        });
        zone_obj.setMap(MAP);
      }
    }, 1000);
  }
</script>

<script>
    (function () {
        renderCharts();
    })();
</script>
{% endblock %}